<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>vip.huizhizao</groupId>
        <artifactId>dofast-module-iot</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>dofast-module-iot-biz</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    
    <dependencies>

        <dependency>
            <groupId>vip.huizhizao</groupId>
            <artifactId>dofast-module-iot-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- 业务组件 -->
        <dependency>
            <groupId>vip.huizhizao</groupId>
            <artifactId>dofast-spring-boot-starter-biz-operatelog</artifactId>
        </dependency>

        <!-- Web 相关 -->
        <dependency>
            <groupId>vip.huizhizao</groupId>
            <artifactId>dofast-spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>vip.huizhizao</groupId>
            <artifactId>dofast-spring-boot-starter-security</artifactId>
        </dependency>

        <!-- DB 相关 -->
        <dependency>
            <groupId>vip.huizhizao</groupId>
            <artifactId>dofast-spring-boot-starter-mybatis</artifactId>
        </dependency>

        <!-- Test 测试相关 -->
        <dependency>
            <groupId>vip.huizhizao</groupId>
            <artifactId>dofast-spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>vip.huizhizao</groupId>
            <artifactId>dofast-spring-boot-starter-excel</artifactId>
        </dependency>

        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.yomahub</groupId>
            <artifactId>liteflow-spring-boot-starter</artifactId>
            <version>2.11.3</version>
        </dependency>
        <dependency>
            <groupId>vip.huizhizao</groupId>
            <artifactId>dofast-module-cmms-api</artifactId>
            <version>1.7.3-snapshot</version>
            <scope>compile</scope>
        </dependency>

        <!-- TDengine连接-->
        <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.2.4</version>
        </dependency>
        <dependency>
            <groupId>vip.huizhizao</groupId>
            <artifactId>dofast-spring-boot-starter-job</artifactId>
        </dependency>

    </dependencies>

</project>